project:
  type: website
  output-dir: docs

website:
  title: "portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/nickjrob
     
format:
  html:
    theme: cosmo
    css: styles.css



