---
title: "Local Advocacy Letter"
author: "Nick Robison"
date: "2025-09-12"
categories: ["WRT 307", projects]
description: "This was an assignment where I had to write a local advocacy letter. I wrote to advocate for more education on human trafficking."
---



LTC Coyne,

I am writing to advocate for further education on and engagement on the issue of human trafficking for the Army ROTC program at Syracuse University. As future leaders in our Army it is imperative that we are cognizant of the signs of human trafficking, understanding its many forms, and learning how to lead soldiers in preventing exploitation, and responding to and supporting the victims of trafficking.

Human trafficking is a complex and pervasive threat. Human trafficking is defined as taking a person via force, fraud, or coercion and exploiting them for a commercial or personal benefit. Under this definition, human trafficking includes things such as sex trafficking (which people often picture when asked about trafficking), labor trafficking, and organ trafficking. This is relevant to the Army because these situations can directly threaten soldiers and the operational security of our units and missions especially due to the sensitive nature and propensity for blackmail associated with sex trafficking and its adjacent crimes such as sexual exploitation.

This issue goes deeper than just personal relevance to soldiers. First, involvement in trafficking is illegal under the Uniform Code of Military Justice, and undermines the readiness and discipline of soldiers and units. Second, trafficking operations are often used to fund or otherwise support terrorist groups that directly threaten our national security (https://humantraffickingsearch.org/human-trafficking-and-the-taliban/). Third, our Army conducts humanitarian and stability missions around the globe. This means our soldiers are likely to encounter trafficking victims and by enhancing our collective ability to recognize and assist victims as well as investigate and facilitate the end of human trafficking around the world builds a foundation of trust with local communities that strengthens U.S. credibility abroad.

To address these challenges we must go beyond the annual training for soldiers. I respectfully request to organize these opportunities for cadets to engage directly with professionals and subject matter experts. I have done a preliminary investigation of three options. These options are a guest lecture, a workshop, or a discussion.

I would greatly appreciate the opportunity to meet and discuss whether integrating one of these opportunities into our ROTC activities is possible and if so which type of opportunity is most feasible.

Respectfully,

Nicholas Robison

CDT, U.S. Army

Syracuse Army ROTC

Email: nrobison\@syr.edu

Phone: (509) - 432 - 6803
