---
title: "International Advocacy Letter"
author: "Nick Robison"
date: "2025-09-16"
categories: ["WRT 307", projects, "Human Trafficking"]
description: "This was an assignment where I had to write an advocacy letter to an international organization. I wrote to the International Organization for Migration to advocate for more education on human trafficking."
---

To the [International Organization for Migration](https://www.iom.int/) (IOM),

I am writing to advocate for more educational opportunities surrounding human trafficking for ROTC cadets. Similarly to IOM, officers will work in foreign settings and must be competent in cross-cultural communication especially on sensitive issues like human trafficking and exploitation. By connecting with and providing resources to ROTC programs, IOM would be cultivating the necessary skills and knowledge to those who work with other governments and communities in a different way. Due to human trafficking’s hidden and pervasive nature we must attack this issue from multiple angles.

IOM provides the opportunity to cadets to learn about this issue and the tools they have to combat it helps by giving another community the necessary insights and perspectives to be leaders in ending human trafficking and the exploitation of victims of any nationality. Human trafficking is a global issue and IOM’s international cooperation is leading the charge in how to combat not only trafficking but any issue that spans across borders.

The U.S. military
