---
title: "Keynote Speaker Invitation"
author: "Nick Robison"
date: "2025-09-17"
categories: ["WRT 307", projects, "Human Trafficking"]
description: "This was an assignment where I had to ask a speaker to come give a keynote speach on the topic I was advocating for. I wrote to Kimberly Mull, a human trafficking survivor and advocate, who speaks professionally on how we can fight human trafficking."
---

Dear Kimberley Mull,

On behalf of Syracuse Army ROTC, I am honored to invite you to serve as the keynote speaker for an upcoming educational event on human trafficking.

Our mission at Syracuse ROTC is to develop military leaders that are prepared to confront our nation's most pressing issues. Human trafficking is one of many pressing issues we are looking to prepare leaders to combat. While we have looked at this issue from a factual and policy perspective, we recognize that this approach alone cannot fully convey the human cost of trafficking. Your willingness to share your personal story and insights would provide cadets with a deeper, more human-centered understanding of trafficking and its devastating effects on individuals, families, and communities.

By hearing your powerful testimony, cadets will not only gain awareness but a greater appreciation for their responsibility to recognize, respond to, and advocate for victims. As future military leaders, they will carry this knowledge and sense of duty into their command positions where they will be able to equip their soldiers with the same awareness and tools to combat trafficking wherever they serve. 

The U.S. military’s global presence and scale makes it highly likely that service members encounter trafficking victims, whether they serve alongside them or in the communities where they operate. Yet many lack the training to identify the signs or respond effectively. Your work to create a culture of safety closely aligns with the values we strive to instill in our cadets. We believe your keynote address would inspire and prepare the next generation of leaders to take meaningful action against human trafficking, both within the force and in the communities they serve.

We would be deeply honored if you would consider joining us for this event.

Respectfully,

Nick Robison


